### ISSUE TITLE
Exercise 1 - suggestions

### ISSUE THREAD

**Issue by kowshiksri** [AndreWeiner/turbulence_modelling_lecture#1]
This is for suggestions and/or corrections for the exercise 1 instruction sheet.

Suggestion 1
Section - Installing OpenFOAM
Current text - "Here you will find an overview of installation options."
Suggested text - "Here you will find an overview of the installation options for both Windows and Linux-based systems."

Suggestion 2
Section - Installing ParaView
Current test - "On Windows, ParaView should not be installed inside WSL."
Suggested text - "On Windows, ParaView should not be installed inside WSL. Rather installation should be done on native Windows and it must be run from Windows when viewing simulation results, even if OpenFOAM is run in WSL."

Suggestion 3
Section - 3
Suggestion - Could there be a need to mention a code editor like Visual Studio Code for the exercises?

**Comment by AndreWeiner** [comment]
Hi @kowshik96,
thanks for the suggestions. I revised the instructions accordingly (see the above commit).
By chance, did you test the instructions for Windows?
Best, Andre

**Comment by kowshiksri** [comment]
Not at this moment but the last time I had done an OpenFOAM installation was at the start of my HiWi and it was on WSL through these same steps and references. It did work that time. Although I must admit it is a hassle to get things to work on WSL.

**Comment by AndreWeiner** [comment]
Can you maybe remember a few points or details of this 'hassle'?

**Comment by kowshiksri** [comment]
It was mostly to do with the following, since the partition on WSL is not very clear: (This is from openfoam.com)

![image](https://user-images.githubusercontent.com/68097874/234040797-5bc25369-05ed-46b0-8c91-69533300d3a8.png)

**Comment by AndreWeiner** [comment]
So you tried to build OpenFOAM from scratch instead of using the Debian (.deb) package? If I understand the instructions correctly, the case sensitivity is only a concern when building OF.

**Comment by kowshiksri** [comment]
Yes I hadn't understood the difference of scratch build and package at the time, and had run into issues post which I stuck to using the package.

**Comment by AndreWeiner** [comment]
Alright, I added another note saying that the standard package installation is sufficient - thanks again for the remarks.
