### ISSUE TITLE
Suggestions for exercises 2&3

### ISSUE THREAD

**Issue by kowshiksri** [AndreWeiner/turbulence_modelling_lecture#2]
Suggestion 1:
Section - Basics of OpenFoam Simulations Part 2
There is a mention of using the test case in the lecture repository but preceding to this there is no documented step of how to clone the repository like we have in the ML-CFD lecture notes.

Suggestion 2:
Section - Laminar flow past a cylinder
In the commands to copy and run the case, there is a comment: "Assuming you are at the repository's top level".
I think for the first instance of this being mentioned, it could be clearly stated what this would mean - like the ml-cfd-lecture top level in the earlier case.

**Comment by kowshiksri** [comment]
Suggestion 3:
Section - Probes
There is a mention to add 3 additional locations of probes. I think the test is not clear enough on which points are to be added. Current text reads - "Add the function object to your controlDict and add three more probeLocations located one diameter d = 0.1m further downstream the cylinder (the main flow direction is along the positive -direction; keep the other two coordinates of the three additional locations the same)."
Potential point of confusion could be the first of the 3 coordinate values at each location. From my understanding of the instructions, this is what I could add: 

![image](https://user-images.githubusercontent.com/68097874/236619524-15a224e9-249a-4075-b1f3-684243891cea.png)

**Comment by kowshiksri** [comment]
Suggestion 4:
Section - Analysis and visualization
A hint could be given on how long one can expect the simulation to run. In my experience on a moderately powered system, this should run somewhere between 10 - 20 mins

**Comment by kowshiksri** [comment]
Suggestion 5:
Section - Analysis of line samples
In the code the path to the line probe is given as below,

![image](https://user-images.githubusercontent.com/68097874/236624409-b4bfee7f-46e7-4cb8-9c14-59e70b3b8135.png)


But when I ran the simulation, I had the path as below,

![image](https://user-images.githubusercontent.com/68097874/236624473-2319fa3b-fca8-4dbc-85c3-0401d63995ae.png)


Difference - the path was './posProcessing/line/2/line1_U.xy'    and not './posProcessing/line/2/line_U.xy'
This could be nothing but just wanted to bring to notice as it would throw error for incorrect file path.

**Comment by AndreWeiner** [comment]
Thanks a lot for the suggestions. I addressed them in the above commit. Let me know if there is anything else to improve.
Best, Andre

**Comment by kowshiksri** [comment]
No that was all the points I could think of.

Thanks
Kowshik
