### ISSUE TITLE
Suggestions for exercise 4

### ISSUE THREAD

**Issue by kowshiksri** [AndreWeiner/turbulence_modelling_lecture#3]
Suggestion 1:
Section: Experimental reference Data
Perhaps a link to the reference article could be given here directly apart from that in the test_case/README.md

Suggestion 2:
Section: Experimental reference Data
When I have the markdown file on VsCode locally, it renders all the equations in the first paragraph starting with text, "Taylor postulated that..."
But on the webpage, it isn't rendering completely. I tried different web browsers and also reloading. Here is how it renders on the webpage:

![image](https://github.com/AndreWeiner/turbulence_modelling_lecture/assets/68097874/d72f12d0-d2db-414e-84c7-16049a4ea9b9)

Maybe this is a local issue, but thought I should just mention in case it isn't.

Suggestion 3:
Section: Experimental reference data
Current text: " Relying on Taylor's hypothesis, they connect positions of the sensors downstream the grid to the time are a parcel of frozen turbulence has traveled along the channel:"
I think there is some text missing after "downstream the grid ..." since the sentence is confusing as is.

**Comment by AndreWeiner** [comment]
Hi Kowshik,
thanks a lot for the remarks. Unfortunately, the rendering on Github is not always the same as in the local Markdown viewer (good catch). I added empty lines before and after the equations, so the rendering should be correct now (at least it is in my browser). Feel free to close this issue if the fixes are sufficient.
Thanks again,
Andre
